# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      
warnings_are_errors: false

before_install:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get update
  - sudo apt-get install libjq-dev
  - sudo apt-get install libprotobuf-dev
  - sudo apt-get install protobuf-compiler libprotobuf-dev libprotoc-dev
  - sudo apt-get install libudunits2-dev
  - sudo apt-get install libv8-3.14-dev

r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
