---
title: "Examples"
author: "John Coene"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

You see the maps available by running the following:

```r
em_bank()
```

Otherwise, the full list of maps is vailable [here](articles/bank.html).

## Basics

There are 215 maps, here are two.

```{r}
library(echarts4r)
library(echarts4r.maps)

jp <- e_charts() %>%
  em_map("Japan") %>% 
  e_map(map = "Japan")

ca <- e_charts() %>%
  em_map("Canada") %>% 
  e_map(map = "Canada")

e_arrange(jp, ca, cols = 2, rows = 1)
```

## Map

Use `em_map` to add the map, simply pass the name of the country, a valid name as returned by `em_bank`, then reference that name in `e_map`.

```{r}
library(echarts4r)
library(echarts4r.maps)

data(state)
state.x77 <- as.data.frame(state.x77)
state.x77$state <- row.names(state.x77)

state.x77 %>% 
  e_charts(state) %>%
  em_map("USA") %>% 
  e_map(Population, map = "USA") %>% 
  e_visual_map(Population)
```

## Map 3D

This will also work in 3d with `e_map_3d`.

```{r}
state.x77 %>% 
  e_charts(state) %>%
  em_map("USA") %>% 
  e_map_3d(Income, map = "USA") %>% 
  e_visual_map(Income)
```

## Geo 3D

And `e_geo_3d`

```{r}
state.x77 %>% 
    e_color_range(Murder, Color) %>% 
    dplyr::mutate(Frost = sqrt(Frost)) %>% 
    e_charts(state) %>%
    em_map("USA") %>% 
    e_geo_3d(Frost, Color, type = "USA") %>% 
    e_visual_map(Frost)
```

## Geo

```{r}
library(echarts4r.maps)

flights <- read.csv(
  paste0("https://raw.githubusercontent.com/plotly/datasets/",
         "master/2011_february_aa_flight_paths.csv")
)

flights %>% 
  e_charts() %>% 
  em_map("USA") %>%
  e_geo("USA") %>% 
  e_lines(
    start_lon, 
    start_lat, 
    end_lon, 
    end_lat,
    name = "flights",
    lineStyle = list(normal = list(curveness = 0.3))
   )
```

## Cities

```{r}
library(dplyr)
data("cities")

cities %>% 
  filter(country == "IN") %>% 
  mutate(val = runif(n(), 1, 3)) %>% 
  e_charts(lon) %>%
  em_map("India") %>% 
  e_geo(map = "India") %>% 
  e_scatter(lat, val, coord_system = "geo", scale = NULL) %>% 
  e_visual_map(min = 1, max = 3)
```